# Generated by Django 3.1.7 on 2021-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=300)),
                ('objectname', models.CharField(max_length=150)),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
